
-- Query 1
-- Retrieve employee information with attendance records

SELECT
    EMPLOYEE.EMP_ID,
    EMPLOYEE.FR_NAME,
    EMPLOYEE.LA_NAME,
    ATTENDANCE.ATT_ID,
    ATTENDANCE.ATT_DATE
FROM EMPLOYEE
JOIN ATTENDANCE
ON EMPLOYEE.EMP_ID = ATTENDANCE.EMP_ID;




-- Query 2
-- Retrieve employee information with break times

SELECT
    EMPLOYEE.EMP_ID,
    EMPLOYEE.FR_NAME,
    EMPLOYEE.LA_NAME,
    BREAK.BREAK_START,
    BREAK.BREAK_END
FROM EMPLOYEE
JOIN ATTENDANCE
ON EMPLOYEE.EMP_ID = ATTENDANCE.EMP_ID
JOIN BREAK
ON ATTENDANCE.ATT_ID = BREAK.ATTENDANCE_ID;




-- Query 3
-- Retrieve requests with manager information

SELECT
    REQUEST.EMP_ID,
    REQUEST.REQ_ID,
    REQUEST.TYPE,
    REQUEST.STATUS,
    MANAGER.FNAME,
    MANAGER.LNAME
FROM REQUEST
JOIN MANAGER
ON REQUEST.M_ID = MANAGER.MANAGERID;




-- Query 4
-- Retrieve approved employee requests

SELECT
    EMPLOYEE.EMP_ID,
    EMPLOYEE.FR_NAME,
    EMPLOYEE.LA_NAME,
    REQUEST.REQ_ID,
    REQUEST.TYPE,
    REQUEST.STATUS
FROM REQUEST
JOIN EMPLOYEE
ON REQUEST.EMP_ID = EMPLOYEE.EMP_ID
WHERE REQUEST.STATUS = 'Approved';



-- Query 5
-- Retrieve rejected employee requests

SELECT
    EMPLOYEE.EMP_ID,
    EMPLOYEE.FR_NAME,
    EMPLOYEE.LA_NAME,
    REQUEST.REQ_ID,
    REQUEST.TYPE,
    REQUEST.STATUS
FROM REQUEST
JOIN EMPLOYEE
ON REQUEST.EMP_ID = EMPLOYEE.EMP_ID
WHERE REQUEST.STATUS = 'Rejected';